import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

const translations = {
  en: {
    // Landing Page
    signIn: 'Sign In',
    register: 'Register',
    transformFinancial: 'Transform Your Financial Mindset',
    buildMindset: 'Build a strong financial mindset and daily money discipline. Think less like an employee and more like an entrepreneur.',
    startJourney: 'Start Your Journey',
    howToMakeMoney: 'How to Make Money Work for You',
    digitalCoach: 'Your Digital Coach for Financial Freedom',
    dailyJournal: 'Daily Journal',
    journalDesc: 'Reflect on your financial actions and decisions every day. Build awareness and learn from each choice.',
    habitsTracker: 'Habits Tracker',
    habitsDesc: 'Track your financial habits consistently. Save, invest, and learn daily. Small actions compound into wealth.',
    visionBoard: 'Vision Board',
    visionDesc: 'Set long-term financial goals and visualize your path to freedom. Make your dreams tangible.',
    readyToChange: 'Ready to Change Your Financial Future?',
    joinThousands: 'Join thousands building their path to financial freedom. Start your transformation today.',
    getStartedFree: 'Get Started Free',
    richMindTagline: 'RichMind Journal - Transform your mindset, transform your wealth.',
    
    // Auth
    login: 'Login',
    email: 'Email',
    password: 'Password',
    dontHaveAccount: "Don't have an account?",
    registerHere: 'Register here',
    alreadyHaveAccount: 'Already have an account?',
    loginHere: 'Login here',
    createAccount: 'Create Account',
    passwordMin: 'Password (min. 8 characters)',
    confirmPassword: 'Confirm Password',
    creatingAccount: 'Creating account...',
    loggingIn: 'Logging in...',
    
    // Dashboard
    welcomeBack: 'Welcome back!',
    everyActionCounts: 'Build your financial mindset one day at a time. Every action counts.',
    journalEntries: 'Journal Entries',
    habitsTracked: 'Habits Tracked',
    goalsSet: 'Goals Set',
    viewJournal: 'View Journal →',
    trackHabits: 'Track Habits →',
    visionBoardLink: 'Vision Board →',
    dailyReflection: 'Daily Reflection',
    writeAboutFinancial: 'Write about your financial actions today. What did you learn? What decisions did you make?',
    writeJournalEntry: 'Write Journal Entry',
    trackYourHabits: 'Track Your Habits',
    recordFinancial: 'Record your financial habits: saving, investing, learning. Consistency builds wealth.',
    trackAHabit: 'Track a Habit',
    recentJournalEntries: 'Recent Journal Entries',
    
    // Journal
    dailyJournalTitle: 'Daily Journal',
    reflectOnJourney: 'Reflect on your financial journey. Write about your actions, decisions, and learnings.',
    newEntry: '+ New Entry',
    cancel: 'Cancel',
    writeYourReflection: 'Write Your Reflection',
    journalPlaceholder: 'What financial actions did you take today? What did you learn? How did you think like an entrepreneur rather than an employee?',
    saveEntry: 'Save Entry',
    saving: 'Saving...',
    noEntriesYet: 'No journal entries yet. Start your financial journey by writing your first reflection!',
    writeFirstEntry: 'Write Your First Entry',
    delete: 'Delete',
    
    // Habits
    habitsTrackerTitle: 'Habits Tracker',
    buildDiscipline: 'Build financial discipline by tracking your daily habits. Consistency is key.',
    trackHabitBtn: '+ Track Habit',
    trackNewHabit: 'Track a New Habit',
    habitType: 'Habit Type',
    notes: 'Notes (optional)',
    notesPlaceholder: 'Add any details about this habit...',
    saveHabit: 'Save Habit',
    recentHabits: 'Recent Habits',
    noHabitsYet: 'No habits tracked yet. Start building your financial discipline today!',
    trackFirstHabit: 'Track Your First Habit',
    savedMoney: 'Saved Money',
    invested: 'Invested',
    learnedSomething: 'Learned Something New',
    trackedExpenses: 'Tracked Expenses',
    readFinancial: 'Read Financial Content',
    networked: 'Networked',
    other: 'Other',
    
    // Vision Board
    visionBoardTitle: 'Vision Board',
    setLongTerm: 'Set your long-term financial goals. Visualize your path to financial freedom.',
    addGoal: '+ Add Goal',
    editGoal: 'Edit Goal',
    addNewGoal: 'Add New Goal',
    yourGoal: 'Your Goal',
    goalPlaceholder: 'E.g., Save $50,000 for investment portfolio by end of year',
    targetDate: 'Target Date (optional)',
    updateGoal: 'Update Goal',
    noGoalsYet: 'No goals set yet. Start visualizing your financial future!',
    addFirstGoal: 'Add Your First Goal',
    edit: 'Edit',
    target: 'Target:',
    created: 'Created:',
    
    // Layout
    logout: 'Logout',
  },
  fr: {
    signIn: 'Se connecter',
    register: "S'inscrire",
    transformFinancial: 'Transformez votre mentalité financière',
    buildMindset: 'Développez une mentalité financière solide et une discipline monétaire quotidienne. Pensez moins comme un employé et plus comme un entrepreneur.',
    startJourney: 'Commencez votre voyage',
    howToMakeMoney: 'Comment faire travailler l\'argent pour vous',
    digitalCoach: 'Votre coach numérique pour la liberté financière',
    dailyJournal: 'Journal quotidien',
    journalDesc: 'Réfléchissez à vos actions et décisions financières chaque jour. Développez la conscience et apprenez de chaque choix.',
    habitsTracker: 'Suivi des habitudes',
    habitsDesc: 'Suivez vos habitudes financières régulièrement. Épargnez, investissez et apprenez quotidiennement. Les petites actions se transforment en richesse.',
    visionBoard: 'Tableau de vision',
    visionDesc: 'Définissez des objectifs financiers à long terme et visualisez votre chemin vers la liberté. Rendez vos rêves tangibles.',
    readyToChange: 'Prêt à changer votre avenir financier?',
    joinThousands: 'Rejoignez des milliers de personnes qui construisent leur chemin vers la liberté financière. Commencez votre transformation aujourd\'hui.',
    getStartedFree: 'Commencer gratuitement',
    richMindTagline: 'RichMind Journal - Transformez votre mentalité, transformez votre richesse.',
    
    login: 'Connexion',
    email: 'Email',
    password: 'Mot de passe',
    dontHaveAccount: "Vous n'avez pas de compte?",
    registerHere: 'Inscrivez-vous ici',
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    loginHere: 'Connectez-vous ici',
    createAccount: 'Créer un compte',
    passwordMin: 'Mot de passe (min. 8 caractères)',
    confirmPassword: 'Confirmer le mot de passe',
    creatingAccount: 'Création du compte...',
    loggingIn: 'Connexion...',
    
    welcomeBack: 'Bon retour!',
    everyActionCounts: 'Développez votre mentalité financière jour après jour. Chaque action compte.',
    journalEntries: 'Entrées de journal',
    habitsTracked: 'Habitudes suivies',
    goalsSet: 'Objectifs définis',
    viewJournal: 'Voir le journal →',
    trackHabits: 'Suivre les habitudes →',
    visionBoardLink: 'Tableau de vision →',
    dailyReflection: 'Réflexion quotidienne',
    writeAboutFinancial: 'Écrivez sur vos actions financières aujourd\'hui. Qu\'avez-vous appris? Quelles décisions avez-vous prises?',
    writeJournalEntry: 'Écrire une entrée de journal',
    trackYourHabits: 'Suivez vos habitudes',
    recordFinancial: 'Enregistrez vos habitudes financières: épargne, investissement, apprentissage. La cohérence construit la richesse.',
    trackAHabit: 'Suivre une habitude',
    recentJournalEntries: 'Entrées de journal récentes',
    
    dailyJournalTitle: 'Journal quotidien',
    reflectOnJourney: 'Réfléchissez à votre parcours financier. Écrivez sur vos actions, décisions et apprentissages.',
    newEntry: '+ Nouvelle entrée',
    cancel: 'Annuler',
    writeYourReflection: 'Écrivez votre réflexion',
    journalPlaceholder: 'Quelles actions financières avez-vous prises aujourd\'hui? Qu\'avez-vous appris? Comment avez-vous pensé comme un entrepreneur plutôt qu\'un employé?',
    saveEntry: 'Enregistrer l\'entrée',
    saving: 'Enregistrement...',
    noEntriesYet: 'Aucune entrée de journal pour le moment. Commencez votre parcours financier en écrivant votre première réflexion!',
    writeFirstEntry: 'Écrivez votre première entrée',
    delete: 'Supprimer',
    
    habitsTrackerTitle: 'Suivi des habitudes',
    buildDiscipline: 'Développez une discipline financière en suivant vos habitudes quotidiennes. La cohérence est essentielle.',
    trackHabitBtn: '+ Suivre une habitude',
    trackNewHabit: 'Suivre une nouvelle habitude',
    habitType: 'Type d\'habitude',
    notes: 'Notes (optionnel)',
    notesPlaceholder: 'Ajoutez des détails sur cette habitude...',
    saveHabit: 'Enregistrer l\'habitude',
    recentHabits: 'Habitudes récentes',
    noHabitsYet: 'Aucune habitude suivie pour le moment. Commencez à développer votre discipline financière aujourd\'hui!',
    trackFirstHabit: 'Suivez votre première habitude',
    savedMoney: 'Argent économisé',
    invested: 'Investi',
    learnedSomething: 'Appris quelque chose de nouveau',
    trackedExpenses: 'Dépenses suivies',
    readFinancial: 'Lu du contenu financier',
    networked: 'Réseauté',
    other: 'Autre',
    
    visionBoardTitle: 'Tableau de vision',
    setLongTerm: 'Définissez vos objectifs financiers à long terme. Visualisez votre chemin vers la liberté financière.',
    addGoal: '+ Ajouter un objectif',
    editGoal: 'Modifier l\'objectif',
    addNewGoal: 'Ajouter un nouvel objectif',
    yourGoal: 'Votre objectif',
    goalPlaceholder: 'Par ex., Économiser 50 000 $ pour un portefeuille d\'investissement d\'ici la fin de l\'année',
    targetDate: 'Date cible (optionnel)',
    updateGoal: 'Mettre à jour l\'objectif',
    noGoalsYet: 'Aucun objectif défini pour le moment. Commencez à visualiser votre avenir financier!',
    addFirstGoal: 'Ajoutez votre premier objectif',
    edit: 'Modifier',
    target: 'Cible:',
    created: 'Créé:',
    
    logout: 'Déconnexion',
  },
  ar: {
    signIn: 'تسجيل الدخول',
    register: 'التسجيل',
    transformFinancial: 'حول عقليتك المالية',
    buildMindset: 'طور عقلية مالية قوية وانضباط مالي يومي. فكر بشكل أقل كموظف وأكثر كرائد أعمال.',
    startJourney: 'ابدأ رحلتك',
    howToMakeMoney: 'كيف تجعل المال يعمل لصالحك',
    digitalCoach: 'مدربك الرقمي للحرية المالية',
    dailyJournal: 'المذكرات اليومية',
    journalDesc: 'تأمل في أفعالك وقراراتك المالية كل يوم. طور الوعي وتعلم من كل خيار.',
    habitsTracker: 'متتبع العادات',
    habitsDesc: 'تتبع عاداتك المالية باستمرار. ادخر واستثمر وتعلم يومياً. الأفعال الصغيرة تتحول إلى ثروة.',
    visionBoard: 'لوحة الرؤية',
    visionDesc: 'حدد أهدافك المالية طويلة الأمد وتصور طريقك إلى الحرية. اجعل أحلامك ملموسة.',
    readyToChange: 'هل أنت مستعد لتغيير مستقبلك المالي?',
    joinThousands: 'انضم إلى الآلاف الذين يبنون طريقهم إلى الحرية المالية. ابدأ تحولك اليوم.',
    getStartedFree: 'ابدأ مجاناً',
    richMindTagline: 'RichMind Journal - حول عقليتك، حول ثروتك.',
    
    login: 'تسجيل الدخول',
    email: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    dontHaveAccount: 'ليس لديك حساب?',
    registerHere: 'سجل هنا',
    alreadyHaveAccount: 'لديك حساب بالفعل?',
    loginHere: 'سجل الدخول هنا',
    createAccount: 'إنشاء حساب',
    passwordMin: 'كلمة المرور (حد أدنى 8 أحرف)',
    confirmPassword: 'تأكيد كلمة المرور',
    creatingAccount: 'جارٍ إنشاء الحساب...',
    loggingIn: 'جارٍ تسجيل الدخول...',
    
    welcomeBack: 'مرحباً بعودتك!',
    everyActionCounts: 'طور عقليتك المالية يوماً بعد يوم. كل فعل مهم.',
    journalEntries: 'إدخالات المذكرات',
    habitsTracked: 'عادات متتبعة',
    goalsSet: 'أهداف محددة',
    viewJournal: 'عرض المذكرات →',
    trackHabits: 'تتبع العادات →',
    visionBoardLink: 'لوحة الرؤية →',
    dailyReflection: 'التأمل اليومي',
    writeAboutFinancial: 'اكتب عن أفعالك المالية اليوم. ماذا تعلمت? ما القرارات التي اتخذتها?',
    writeJournalEntry: 'اكتب إدخالاً في المذكرات',
    trackYourHabits: 'تتبع عاداتك',
    recordFinancial: 'سجل عاداتك المالية: الادخار، الاستثمار، التعلم. الاتساق يبني الثروة.',
    trackAHabit: 'تتبع عادة',
    recentJournalEntries: 'إدخالات المذكرات الأخيرة',
    
    dailyJournalTitle: 'المذكرات اليومية',
    reflectOnJourney: 'تأمل في رحلتك المالية. اكتب عن أفعالك وقراراتك وتعلمك.',
    newEntry: '+ إدخال جديد',
    cancel: 'إلغاء',
    writeYourReflection: 'اكتب تأملاتك',
    journalPlaceholder: 'ما الإجراءات المالية التي اتخذتها اليوم? ماذا تعلمت? كيف فكرت كرائد أعمال بدلاً من موظف?',
    saveEntry: 'حفظ الإدخال',
    saving: 'جارٍ الحفظ...',
    noEntriesYet: 'لا توجد إدخالات مذكرات بعد. ابدأ رحلتك المالية بكتابة تأملاتك الأولى!',
    writeFirstEntry: 'اكتب إدخالك الأول',
    delete: 'حذف',
    
    habitsTrackerTitle: 'متتبع العادات',
    buildDiscipline: 'طور الانضباط المالي من خلال تتبع عاداتك اليومية. الاتساق هو المفتاح.',
    trackHabitBtn: '+ تتبع عادة',
    trackNewHabit: 'تتبع عادة جديدة',
    habitType: 'نوع العادة',
    notes: 'ملاحظات (اختياري)',
    notesPlaceholder: 'أضف أي تفاصيل حول هذه العادة...',
    saveHabit: 'حفظ العادة',
    recentHabits: 'العادات الأخيرة',
    noHabitsYet: 'لا توجد عادات متتبعة بعد. ابدأ بناء انضباطك المالي اليوم!',
    trackFirstHabit: 'تتبع عادتك الأولى',
    savedMoney: 'مال مدخر',
    invested: 'مستثمر',
    learnedSomething: 'تعلمت شيئاً جديداً',
    trackedExpenses: 'مصروفات متتبعة',
    readFinancial: 'قرأت محتوى مالياً',
    networked: 'تواصلت',
    other: 'أخرى',
    
    visionBoardTitle: 'لوحة الرؤية',
    setLongTerm: 'حدد أهدافك المالية طويلة الأمد. تصور طريقك إلى الحرية المالية.',
    addGoal: '+ إضافة هدف',
    editGoal: 'تعديل الهدف',
    addNewGoal: 'إضافة هدف جديد',
    yourGoal: 'هدفك',
    goalPlaceholder: 'مثلاً، ادخر 50,000 دولار لمحفظة استثمارية بحلول نهاية العام',
    targetDate: 'التاريخ المستهدف (اختياري)',
    updateGoal: 'تحديث الهدف',
    noGoalsYet: 'لا توجد أهداف محددة بعد. ابدأ تصور مستقبلك المالي!',
    addFirstGoal: 'أضف هدفك الأول',
    edit: 'تعديل',
    target: 'الهدف:',
    created: 'تم الإنشاء:',
    
    logout: 'تسجيل الخروج',
  },
  es: {
    signIn: 'Iniciar sesión',
    register: 'Registrarse',
    transformFinancial: 'Transforma tu mentalidad financiera',
    buildMindset: 'Desarrolla una mentalidad financiera sólida y disciplina monetaria diaria. Piensa menos como empleado y más como empresario.',
    startJourney: 'Comienza tu viaje',
    howToMakeMoney: 'Cómo hacer que el dinero trabaje para ti',
    digitalCoach: 'Tu entrenador digital para la libertad financiera',
    dailyJournal: 'Diario diario',
    journalDesc: 'Reflexiona sobre tus acciones y decisiones financieras cada día. Desarrolla consciencia y aprende de cada elección.',
    habitsTracker: 'Rastreador de hábitos',
    habitsDesc: 'Rastrea tus hábitos financieros consistentemente. Ahorra, invierte y aprende diariamente. Las pequeñas acciones se convierten en riqueza.',
    visionBoard: 'Tablero de visión',
    visionDesc: 'Establece metas financieras a largo plazo y visualiza tu camino hacia la libertad. Haz tus sueños tangibles.',
    readyToChange: '¿Listo para cambiar tu futuro financiero?',
    joinThousands: 'Únete a miles construyendo su camino hacia la libertad financiera. Comienza tu transformación hoy.',
    getStartedFree: 'Comenzar gratis',
    richMindTagline: 'RichMind Journal - Transforma tu mentalidad, transforma tu riqueza.',
    
    login: 'Iniciar sesión',
    email: 'Correo electrónico',
    password: 'Contraseña',
    dontHaveAccount: '¿No tienes una cuenta?',
    registerHere: 'Regístrate aquí',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    loginHere: 'Inicia sesión aquí',
    createAccount: 'Crear cuenta',
    passwordMin: 'Contraseña (mín. 8 caracteres)',
    confirmPassword: 'Confirmar contraseña',
    creatingAccount: 'Creando cuenta...',
    loggingIn: 'Iniciando sesión...',
    
    welcomeBack: '¡Bienvenido de nuevo!',
    everyActionCounts: 'Desarrolla tu mentalidad financiera día a día. Cada acción cuenta.',
    journalEntries: 'Entradas del diario',
    habitsTracked: 'Hábitos rastreados',
    goalsSet: 'Metas establecidas',
    viewJournal: 'Ver diario →',
    trackHabits: 'Rastrear hábitos →',
    visionBoardLink: 'Tablero de visión →',
    dailyReflection: 'Reflexión diaria',
    writeAboutFinancial: 'Escribe sobre tus acciones financieras hoy. ¿Qué aprendiste? ¿Qué decisiones tomaste?',
    writeJournalEntry: 'Escribir entrada del diario',
    trackYourHabits: 'Rastrea tus hábitos',
    recordFinancial: 'Registra tus hábitos financieros: ahorrar, invertir, aprender. La consistencia construye riqueza.',
    trackAHabit: 'Rastrear un hábito',
    recentJournalEntries: 'Entradas recientes del diario',
    
    dailyJournalTitle: 'Diario diario',
    reflectOnJourney: 'Reflexiona sobre tu viaje financiero. Escribe sobre tus acciones, decisiones y aprendizajes.',
    newEntry: '+ Nueva entrada',
    cancel: 'Cancelar',
    writeYourReflection: 'Escribe tu reflexión',
    journalPlaceholder: '¿Qué acciones financieras tomaste hoy? ¿Qué aprendiste? ¿Cómo pensaste como empresario en lugar de empleado?',
    saveEntry: 'Guardar entrada',
    saving: 'Guardando...',
    noEntriesYet: 'Aún no hay entradas del diario. ¡Comienza tu viaje financiero escribiendo tu primera reflexión!',
    writeFirstEntry: 'Escribe tu primera entrada',
    delete: 'Eliminar',
    
    habitsTrackerTitle: 'Rastreador de hábitos',
    buildDiscipline: 'Desarrolla disciplina financiera rastreando tus hábitos diarios. La consistencia es clave.',
    trackHabitBtn: '+ Rastrear hábito',
    trackNewHabit: 'Rastrear un nuevo hábito',
    habitType: 'Tipo de hábito',
    notes: 'Notas (opcional)',
    notesPlaceholder: 'Agrega detalles sobre este hábito...',
    saveHabit: 'Guardar hábito',
    recentHabits: 'Hábitos recientes',
    noHabitsYet: 'Aún no hay hábitos rastreados. ¡Comienza a desarrollar tu disciplina financiera hoy!',
    trackFirstHabit: 'Rastrea tu primer hábito',
    savedMoney: 'Dinero ahorrado',
    invested: 'Invertido',
    learnedSomething: 'Aprendió algo nuevo',
    trackedExpenses: 'Gastos rastreados',
    readFinancial: 'Leyó contenido financiero',
    networked: 'Conectó',
    other: 'Otro',
    
    visionBoardTitle: 'Tablero de visión',
    setLongTerm: 'Establece tus metas financieras a largo plazo. Visualiza tu camino hacia la libertad financiera.',
    addGoal: '+ Agregar meta',
    editGoal: 'Editar meta',
    addNewGoal: 'Agregar nueva meta',
    yourGoal: 'Tu meta',
    goalPlaceholder: 'Ej., Ahorrar $50,000 para cartera de inversiones para fin de año',
    targetDate: 'Fecha objetivo (opcional)',
    updateGoal: 'Actualizar meta',
    noGoalsYet: 'Aún no hay metas establecidas. ¡Comienza a visualizar tu futuro financiero!',
    addFirstGoal: 'Agrega tu primera meta',
    edit: 'Editar',
    target: 'Objetivo:',
    created: 'Creado:',
    
    logout: 'Cerrar sesión',
  },
}

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    () => localStorage.getItem('language') || 'en'
  )

  useEffect(() => {
    localStorage.setItem('language', language)
    document.documentElement.lang = language
    // Set direction for Arabic
    if (language === 'ar') {
      document.documentElement.dir = 'rtl'
    } else {
      document.documentElement.dir = 'ltr'
    }
  }, [language])

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

